# --- just ---
# Command runner plus completion generated by the same pinned package.
{ pkgs, ... }:
{
  home.packages = [ pkgs.just ];

  home.file.".local/share/zsh/site-functions/_just".source =
    "${pkgs.just}/share/zsh/site-functions/_just";
}
